### ISSUE TITLE
민준이형과 협곡 플레 찍기..? 

### ISSUE THREAD

**Issue by moto6** [NamWoo/life-plan#1]
지금은 안한지 4년쯤 되서, 티어는 아이언 밑바닥 심해

평생동안 브실골 광물을 벗어나본적없는 리얼트루참트루 현지인

친구랑 듀오로 골2>>1 넘어가는 승급전에서 미끄러진 이후로 그대로 롤접

평균 실버 3~4 정도

**Comment by NamWoo** [comment]
ㅋㅋㅋㅋ 여기 화석 1인 추가

**Comment by moto6** [comment]
남우형 라벨이 버그라닠 ㅋㅋㅋ
